src/Entity/Contact.php
<?php
declare(strict_types=1);

namespace App\Entity;

use DateTime;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\Contact")
 * @ORM\Table(name="app_contact")
 */

class Contact 
{   
    /**
    * @ORM\Id()
    * @ORM\GeneratedValue() 
    * @ORM\Column(type="integer")
    */
    private $id;

    
    /**
     * @ORM\Column(type="string",length=255)
     */
    private $firstname;

    
    /**
     * @ORM\Column(type="string",length=255)
     */
    private $lastname;


    /**
     * @ORM\Column(type="string",length=255)
     */
    private $email;

    /**
     * @ORM\Column(type="text")
     */
    private $message;

     /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    public function __construct()
    {
        $this->created_at = new \DateTime();
    }

    public function getId()
    {
        return $this->id;
    }

    public function setId(string $id)
    {
        return $this->id = $id;
    }
    
    public function getFirstName()
    {
        return $this->firstname;
    }

    public function setFirstName(string $firstname)
    {
        return $this->firstname = $firstname;
    }

    
    public function getLastName()
    {
        return $this->lastname;
    }

    public function setLastName(string $lastname)
    {
        return $this->lastname = $lastname;
    }

    
    public function getEmail()
    {
        return $this->email;
    }

    public function setEmail(string $email)
    {
        return $this->email = $email;
    }

    
    public function getMessage()
    {
        return $this->message;
    }

    public function setMessage(string $message)
    {
        return $this->message = $message;
    }

    public function getCreatedAt(): ?\DateTime
    {
        return $this->created_at;
    }

    public function setCreatedAt(DateTime $created_at): self
    {
        $this->created_at = $created_at;
        return $this;
    }
    


}

src/Controller/MainController.php
<?php

namespace App\Controller;

use App\Repository\Store\ProductRepository;

use App\Entity\Contact;
use App\Form\ContactType;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

use App\Mailer\ContactMailer;
use Doctrine\ORM\EntityManagerInterface;

class MainController extends AbstractController 
{

    public function __construct(
        private ContactMailer $mailer, 
        private EntityManagerInterface $em, 
        private ProductRepository $productRepository)
    {
    }   

    /** 
     * @Route("/",name="main_homepage",methods={"GET"})
     */

    public function main() : Response
    {
        
        $productsRecent =  $this->productRepository->findByNameAndCreatedAt();
        $productsCurrent =  $this->productRepository->whereCurrentYear();
      
        return $this->render('main/index.html.twig',[
            'title' => "Homepage",
            'productsR' => $productsRecent,
            'productsC' => $productsCurrent,
        ]);
    }

    /** 
     * @Route("/presentation",name="main_presentation",methods={"GET"})
     */

    public function presentation() : Response
    {
        return $this->render('main/presentation.html.twig',[
            'title' => "Presentation",
        ]);
    }

     /** 
     * @Route("/contact",name="main_contact",methods={"GET","POST"})
     */

    public function contact(Request $request) : Response
    {

        $contact = new Contact();

        $form = $this->createForm(ContactType::class, $contact);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->em->persist($contact);
            $this->em->flush();

            $this->addFlash('success', 'Merci, votre message a bien été pris en compte !');
            // $this->mailer->sendMail($contact);
            return $this->redirectToRoute('main_contact');
        }

        return $this->render('main/contact.html.twig',[
            'title' => "Contact",
            'form' => $form->createView()
        ]);
    }
}

templates/main/contact.html.twig
{% extends 'layout.html.twig' %}
    {% block content %}
            <div class="row">
                <div class="col-lg-12">
                    <h1>Contactez notre service client</h1>
                </div>
            </div>
    
            <hr/>

            {% for message in app.flashes('success') %}
                <div class="alert alert-success" role="alert">
                    {{ message }}
                </div>
                <hr>
            {% endfor %}

        
            {{ form_start(form) }}
                <div class="form-group">
                    {{ form_errors(form.firstName) }}
                    {{ form_label(form.firstName) }}
                    {{ form_widget(form.firstName, {'attr': {'class': 'form-control', 'placeholder':form.firstName.vars.label} }) }}
                </div>
                <div class="form-group">
                    {{ form_errors(form.lastName) }}
                    {{ form_label(form.lastName) }}
                    {{ form_widget(form.lastName, {'attr': {'class': 'form-control', 'placeholder':form.lastName.vars.label} }) }}
                </div>
                <div class="form-group">
                    {{ form_errors(form.email) }}
                    {{ form_label(form.email) }}
                    {{ form_widget(form.email, {'attr': {'class': 'form-control', 'placeholder':form.email.vars.label} }) }}
                </div>
                <div class="form-group">
                    {{ form_errors(form.message) }}
                    {{ form_label(form.message) }}
                    {{ form_widget(form.message, {'attr': {'class': 'form-control', 'placeholder':form.message.vars.label} }) }}
                </div>
                <button type="submit" class="btn btn-info"> Envoyer mon message </button>
            {{ form_end(form) }}

            <hr/>

{% endblock %}

templates/main/index.html.twig
{% extends 'layout.html.twig' %}
    {% block content %}
        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                <li data-target="#carousel-example-generic" data-slide-to="1"></li>
            </ol>

            <div class="carousel-inner" role="listbox">
                <div class="item active">
                    <img src="img/slides/slide-1.jpg" alt="Slide 1">
                </div>
                <div class="item">
                    <img src="img/slides/slide-2.jpg" alt="Slide 2">
                </div>
            </div>

            <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                <span class="sr-only">Précédent</span>
            </a>
            <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                <span class="sr-only">Suivant</span>
            </a>
        </div>

        <hr/>

        <div class="row">
                <div class="col-lg-12">
                    <h3>Les nouveautés</h3>
                </div>
            </div>
            <div class="row text-center">
            {% for product in productsR %}
                {{include('main/product-item.html.twig')}}
            {% endfor %}
            </div>

            <hr/>
    
            <div class="row">
                <div class="col-lg-12">
                    <h3>Les plus populaires</h3>
                </div>
            </div>
            
            <div class="row text-center">
            {% for product in productsC %}
                {{include('main/product-item.html.twig')}}
            {% endfor %}
            </div>

            <hr/>

    {% endblock %}

templates/main/presentation.html.twig
{% extends 'layout.html.twig' %}
    {% block content %}
            <div class="row">
                <div class="col-lg-12">
                    <h1>Shoefony, l'univers du sport</h1>
                </div>
            </div>

            <hr/>

        	<div class="row">
        		<div class="col-md-5">
		        	<img class="img-responsive" src="img/shop.jpg" alt="Shoe-fony boutique" />
		        </div>
		        <div class="col-md-7">
		        	<h2 class="featurette-heading">First featurette heading. <span class="text-muted">It'll blow your mind.</span></h2>
		        	<p class="lead">
		          		Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo. Donec ullamcorper nulla non metus auctor fringilla.
		        	</p>
		        </div>
	      	</div>

	      	<hr/>

            <div class="row">
		        <div class="col-md-7">
		        	<h2 class="featurette-heading">First featurette heading. <span class="text-muted">It'll blow your mind.</span></h2>
		        	<p class="lead">
		          		Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo. Donec ullamcorper nulla non metus auctor fringilla.
		        	</p>
		        	<p class="lead">
		          		Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo. Donec ullamcorper nulla non metus auctor fringilla.
		        	</p>
		        </div>
		        <div class="col-md-5">
		        	<img class="img-responsive" src="img/team.jpg" alt="Shoe-fony équipe" />
		        </div>
	      	</div>

            <hr/>
            
{% endblock %}

templates/main/product-item.html.twig
<div class="col-md-3 col-sm-6 hero-feature">
	<div class="thumbnail">
		<img src="{{ asset('' ~ product.image.url ~ '') }}" alt="{{ product.image.alt }}">
		<div class="caption">
			<h3> {{ product.name }} </h3>
			<p>{{ product.description }}</p>
			<p>
				<span class="badge">{{ product.price }}€</span>
				<a href=" {{ asset('/store/product/' ~ product.id ~ '/details/' ~ product.slug ~ '') }}" class="btn btn-default">Voir la fiche</a>
			</p>
		</div>
	</div>
</div>